global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "ms-eureka"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["eureka:8080"]
  - job_name: "ms-gateway"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["ms-gateway:8080"]
  - job_name: "ms-cart"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["ms-cart:8080"]
  - job_name: "ms-email"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["ms-email:8080"]
  - job_name: "ms-product"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["ms-product:8080"]
  - job_name: "ms-search"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["ms-search:8080"]
  - job_name: "ms-stripe"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ "ms-stripe:8080" ]
  - job_name: "ms-user"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ "ms-user:8080" ]