server:
  port: 9008
  servlet:
    context-path: /

spring:
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    aws:
      region:
        static: ${AWS_REGION}
      credentials:
        access-key: ${ACCESS_KEY}
        secret-key: ${SECRET_KEY}
      sns:
        enabled: true
        region: ${AWS_REGION}
        endpoint: ${SNS_ENDPOINT}

stripe:
  secret-key: ${STRIPE_SECRET_KEY}
  publishable-key: ${STRIPE_PUBLISHABLE_KEY}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET}
  frontend-endpoint: ${FRONTEND_ENDPOINT}

aws:
  sns:
    arn: ${SNS_TOPIC_ARN}

springdoc:
  api-docs:
    enabled: true
    path: /docs/v3/stripe/api-docs
  swagger-ui:
    path: /docs/v3/stripe/swagger-ui/index.html

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9002/eureka/
