spring:
  application:
    name: cart
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ms-cart

endpoints:
  shutdown:
    enabled: true

info:
  app:
    name: "ms-cart"
    description: "Digital Hippo CART microservice application"
    version: "0.0.1"