server:
  port: 9004

spring:
  application:
    name: user
  # x86 device use this configuration
#  redis:
#    host: ${REDIS_HOST}
#    port: ${REDIS_PORT}
#    password: ${REDIS_PASSWORD}
#    database: ${REDIS_SESSION_DATABASE}
  # mac device with ARM chip use this configuration
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      database: ${REDIS_SESSION_DATABASE}
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: true
  cloud:
    aws:
      region:
        static: ${AWS_REGION}
      credentials:
        access-key: ${ACCESS_KEY}
        secret-key: ${SECRET_KEY}
      sns:
        enabled: true
        region: ${AWS_REGION}

aws:
  sns:
    arn: ${SNS_TOPIC_ARN}

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9002/eureka/