server:
  port: 9004

spring:
  application:
    name: user
  datasource:
    url: jdbc:postgresql://localhost:5432/digitalhippo
    username: postgres
    password: 1234567890
  jpa:
    show-sql: true
  redis:
    host: localhost
    port: 6379
    password: 1234
    database: 1
  cloud:
    aws:
      region:
        static: ${AWS_REGION}
      credentials:
        access-key: ${ACCESS_KEY}
        secret-key: ${SECRET_KEY}
      sqs:
        enabled: true
        endpoint: ${SQS_ENDPOINT}
        region: ${AWS_REGION}

aws:
  sqs:
    name: ${SQS_QUEUE_NAME}

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9002/eureka/