install:
  runtime-versions:
    docker: 19 # specify Docker version 19 as the application runtime
  commands:
    - echo Installing Maven and dependencies # install maven and dependencies
    - mvn install -DskipTests
  pre_build:
    commands:
      - echo Logging in to Amazon ECR... # log in to Amazon Elastic Container Registry
      - $(aws ecr get-login --no-include-email --region $ECR_REGION)
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install
      # build image for eureka microservice
      - echo Building the Docker image for ms eureka-server...
      - cd eureka-server # navigate to our application directory
      - mvn compile jib:dockerBuild # create the Docker image, tagging it appropriately
      - docker tag digitalhippo/eureka:latest $EUREKA_ECR_URI:latest
      # gateway microservice
      - echo Building the Docker image for ms gateway...
      - cd ../server-gateway
      - mvn compile jib:dockerBuild
      - docker tag digitalhippo/gateway:latest $GATEWAY_ECR_URI:latest
      # user microservice
      - echo Building the Docker image for ms user...
      - cd ../service/user
      - mvn compile jib:dockerBuild
      - docker tag digitalhippo/user:latest $USER_ECR_URI:latest
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push digitalhippo/eureka:latest # push new docker image to ECR
      - docker push digitalhippo/gateway:latest
      - docker push digitalhippo/user:latest