apiVersion: v1
kind: Secret
metadata:
  name: digitalhippo-secrets
  namespace: digitalhippo
type: Opaque
data:
  AWS_ACCESS_KEY_ID: dGVzdA==
  AWS_SECRET_ACCESS_KEY: dGVzdA==
  SNS_TOPIC_NAME: dGVzdA==
  SNS_TOPIC_ARN: dGVzdA==
  SNS_ENDPOINT: dGVzdA==
  DLQ_QUEUE_NAME: dGVzdA==
  SQS_ENDPOINT: dGVzdA==
  RECEIPT_SQS_QUEUE_NAME: dGVzdA==
  RECEIPT_SQS_QUEUE_URL: dGVzdA==
  VERIFICATION_SQS_QUEUE_NAME: dGVzdA==
  VERIFICATION_SQS_QUEUE_URL: dGVzdA==
  AWS_S3_ENDPOINT: dGVzdA==
  AWS_S3_BUCKET_NAME: dGVzdA==
  STRIPE_WEBHOOK_SECRET: dGVzdA==
  STRIPE_PUBLISHABLE_KEY: dGVzdA==
  STRIPE_SECRET_KEY: dGVzdA==
  GMAIL_USERNAME: dGVzdA==
  GOOGLE_APP_PASSWORD: dGVzdA==
  MONGODB_PASSWORD: dGVzdA==
  MONGODB_URL: dGVzdA==
  MONGO_INITDB_ROOT_USERNAME: dGVzdA==
  REDIS_HOST: dGVzdA==
  REDIS_PORT: dGVzdA==
  REDIS_PASSWORD: dGVzdA==
  POSTGRES_URL: dGVzdA==
  POSTGRES_USER: dGVzdA==
  POSTGRES_PASSWORD: dGVzdA==
  ES_ENDPOINT: DGDGDGDGD
  kibana.yml: |
    aaaaa: ""
  logstash.yml: |
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
    xpack.monitoring.enabled: true
    xpack.monitoring.elasticsearch.hosts: [ "***********" ]
  logstash.conf: |
    input {
        tcp{
            port => 5000
            codec => json
        }
    }
      output{
      elasticsearch{
      hosts => ["***********"]
      index => "digitalhippo-logs-%{microservice}"
      }
    }
