server:
  port: 8080
  servlet:
    context-path: /

spring:
  devtools:
    remote:
      restart:
        enabled: false
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      database: ${REDIS_CACHING_DATABASE}
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  elasticsearch:
    uris:
      - ${ES_ENDPOINT}

springdoc:
  api-docs:
    enabled: true
    path: /docs/v3/product/api-docs
  swagger-ui:
    path: /docs/v3/product/swagger-ui/index.html

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka:8080/eureka/
    enabled: false