apiVersion: v1
kind: ConfigMap
metadata:
  name: digitalhippo-aws-config-map
  namespace: digitalhippo
data:
  AWS_REGION: "ca-central-1"
  AWS_ENDPOINT: "http://localstack-dh:4566"
  LOCALSTACK_ENDPOINT: "http://localstack-dh:4566"
  LOCALSTACK_HOST: "localstack-dh"
  SNS_TOPIC_NAME: "digitalhippo-email-topic"
  SNS_TOPIC_ARN: "arn:aws:sns:ca-central-1:000000000000:digitalhippo-email-topic"
  #  SNS_ENDPOINT: "arn:aws:sns:ca-central-1:000000000000:digitalhippo-email-topic"
  SNS_ENDPOINT: "http://localstack-dh:4566"
  DLQ_QUEUE_NAME: "digitalhippo-email-dlq"
  RECEIPT_SQS_QUEUE_NAME: "digitalhippo-receipt-email-queue"
  RECEIPT_SQS_QUEUE_URL: "http://sqs.ca-central-1.localstack-dh:4566/000000000000/digitalhippo-receipt-email-queue"
  VERIFICATION_SQS_QUEUE_NAME: "digitalhippo-verification-email-queue"
  VERIFICATION_SQS_QUEUE_URL: "http://sqs.ca-central-1.localstack-dh:4566/000000000000:digitalhippo-verification-email-queue"
  AWS_S3_ENDPOINT: "http://localstack-dh:4566"
  SQS_ENDPOINT: "http://localstack-dh:4566"
  AWS_S3_BUCKET_NAME: "digitalhippo-leopoldxing"
  public-read-policy.json: |
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Effect": "Allow",
          "Principal": "*",
          "Action": "s3:GetObject",
          "Resource": "arn:aws:s3:::digitalhippo-leopoldxing/*"
        }
      ]
    }
