server:
  port: 8080

spring:
  mail:
    host: ${SMTP_PROVIDER_HOST}
    port: ${SMTP_PROVIDER_PORT}
    username: ${SMTP_PROVIDER_USERNAME}
    password: ${SMTP_PROVIDER_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS}

springdoc:
  api-docs:
    enabled: true
    path: /docs/v3/notification/api-docs
  swagger-ui:
    path: /docs/v3/notification/swagger-ui/index.html

email:
  frontend-endpoint: ${FRONTEND_ENDPOINT}

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka:8080/eureka/