server:
  port: 9005

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: xxxxxx@gmail.com
    password: "xxxxxxxxxxxxxxx"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    bootstrap-servers: localhost:9094

springdoc:
  api-docs:
    enabled: true
    path: /docs/v3/notification/api-docs
  swagger-ui:
    path: /docs/v3/notification/swagger-ui/index.html

email:
  frontend-endpoint: http://localhost:5379

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9002/eureka/