apiVersion: v1
kind: ConfigMap
metadata:
  name: digitalhippo-config-map
  namespace: digitalhippo
data:
  # testing dependencies
  # cluster info
  SPRING_PROFILES_ACTIVE: "prod"
  EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: "http://eureka-server:9002/eureka"
  EUREKA_APPLICATION_NAME: "eureka-server"
  USER_APPLICATION_NAME: "user"
  PRODUCT_APPLICATION_NAME: "product"
  GATEWAY_APPLICATION_NAME: "gateway"
  EMAIL_APPLICATION_NAME: "email"
  ORDER_APPLICATION_NAME: "order"
  kibana.yml: |
    server.host: "0.0.0.0"
    server.port: 5601
    elasticsearch.hosts: [ "http://elasticsearch:9200" ]
    monitoring.ui.container.elasticsearch.enabled: true
