apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-gateway
  namespace: digitalhippo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-gateway
  template:
    metadata:
      labels:
        app: server-gateway
    spec:
      containers:
        - name: server-gateway
          image: digitalhippo/gateway:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: digitalhippo-secrets
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: digitalhippo-secrets
                  key: REDIS_PORT
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: digitalhippo-secrets
                  key: REDIS_PASSWORD
            - name: REDIS_SESSION_DATABASE
              valueFrom:
                secretKeyRef:
                  name: digitalhippo-secrets
                  key: REDIS_SESSION_DATABASE
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: server-gateway
  namespace: digitalhippo
spec:
  selector:
    app: server-gateway
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080