apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  namespace: digitalhippo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          image: digitalhippo/eureka:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9002
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  namespace: digitalhippo
spec:
  selector:
    app: eureka-server
  type: ClusterIP
  ports:
    - port: 9002
      targetPort: 9002