apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack-dh
  namespace: digitalhippo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localstack-dh
  template:
    metadata:
      labels:
        app: localstack-dh
    spec:
      containers:
        - name: localstack-dh
          image: localstack/localstack:3.8
          ports:
            - containerPort: 4566
          env:
            - name: SERVICES
              value: "s3,sns,sqs"
            - name: DEBUG
              value: "1"
            - name: LOCALSTACK_HOST
              value: "localhost"
        - name: aws-cli-dh
          image: amazon/aws-cli
          env:
            - name: AWS_ACCESS_KEY_ID
              value: "test"
            - name: AWS_SECRET_ACCESS_KEY
              value: "test"
            - name: AWS_DEFAULT_REGION
              value: "ca-central-1"
          command: ["/bin/sh", "-c"]
          args:
            - |
              until curl -s http://localstack-dh:4566; do echo waiting for localstack; sleep 5; done;
              aws --endpoint-url=http://localstack-dh:4566 sns create-topic --name digitalhippo-email-topic &&
              aws --endpoint-url=http://localstack-dh:4566 sqs create-queue --queue-name digitalhippo-receipt-email-queue &&
              aws --endpoint-url=http://localstack-dh:4566 sqs create-queue --queue-name digitalhippo-verification-email-queue &&
              aws --endpoint-url=http://localstack-dh:4566 sns subscribe --topic-arn arn:aws:sns:us-east-1:000000000000:digitalhippo-email-topic --protocol sqs --notification-endpoint arn:aws:sqs:us-east-1:000000000000:digitalhippo-receipt-email-queue &&
              aws --endpoint-url=http://localstack-dh:4566 sns subscribe --topic-arn arn:aws:sns:us-east-1:000000000000:digitalhippo-email-topic --protocol sqs --notification-endpoint arn:aws:sqs:us-east-1:000000000000:digitalhippo-verification-email-queue &&
              aws --endpoint-url=http://localstack-dh:4566 s3 mb s3://digitalhippo-leopoldxing &&
              aws --endpoint-url=http://localstack-dh:4566 s3api put-bucket-policy --bucket digitalhippo-leopoldxing --policy file:///public-read-policy.json
          volumeMounts:
            - name: aws-init-scripts
              mountPath: /public-read-policy.json
              subPath: public-read-policy.json
      volumes:
        - name: aws-init-scripts
          configMap:
            name: digitalhippo-aws-config-map
---
apiVersion: v1
kind: Service
metadata:
  name: localstack-dh
  namespace: digitalhippo
spec:
  selector:
    app: localstack-aws-init
  ports:
    - port: 4566
      targetPort: 4566
  type: ClusterIP
