apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-dh
  namespace: digitalhippo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana-dh
  template:
    metadata:
      labels:
        app: kibana-dh
    spec:
      containers:
        - name: kibana-dh
          image: kibana:8.14.1
          ports:
            - containerPort: 5601
          volumeMounts:
            - name: kibana-config
              mountPath: /usr/share/kibana/config/kibana.yml
              subPath: kibana.yml
      volumes:
        - name: kibana-config
          configMap:
            name: digitalhippo-elk-config-map
---
apiVersion: v1
kind: Service
metadata:
  name: kibana-dh
  namespace: digitalhippo
spec:
  type: NodePort
  selector:
    app: kibana-dh
  ports:
    - name: http
      port: 5601
      targetPort: 5601
      nodePort: 31100
