apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-dh
  namespace: digitalhippo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-dh
  template:
    metadata:
      labels:
        app: redis-dh
    spec:
      containers:
        - name: redis-dh
          image: redis:7.0.14
          ports:
            - containerPort: 6379
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: digitalhippo-secrets
                  key: REDIS_PASSWORD
          args: [ "redis-server", "--requirepass", "$(REDIS_PASSWORD)" ]
---
apiVersion: v1
kind: Service
metadata:
  name: redis-dh
  namespace: digitalhippo
spec:
  selector:
    app: redis-dh
  ports:
    - name: redis-dh
      port: 6379
      targetPort: 6379
