server:
  port: 9003

spring:
  application:
    name: search
  elasticsearch:
    uris:
      - ${ES_ENDPOINT}

springdoc:
  api-docs:
    enabled: true
    path: /docs/v3/search/api-docs
  swagger-ui:
    path: /docs/v3/search/swagger-ui/index.html

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9002/eureka/