apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-dh
  namespace: digitalhippo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-dh
  template:
    metadata:
      labels:
        app: grafana-dh
    spec:
      containers:
        - name: grafana-dh
          image: grafana/grafana:11.2.2
          env:
            - name: GF_PATHS_PROVISIONING
              value: /etc/grafana/provisioning
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"
            - name: GF_AUTH_ANONYMOUS_ORG_ROLE
              value: "Admin"
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: grafana-datasources
              mountPath: /etc/grafana/provisioning/datasources/datasource.yml
              subPath: datasource.yml
      volumes:
        - name: grafana-datasources
          configMap:
            name: digitalhippo-general-config-map
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-dh
  namespace: digitalhippo
spec:
  type: NodePort
  selector:
    app: grafana-dh
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 31406
