spring:
  application:
    name: eureka
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      enabled: false
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ms-eureka

endpoints:
  shutdown:
    enabled: false

info:
  app:
    name: "eureka"
    description: "Digital Hippo EUREKA microservice application"
    version: "0.0.1"