server:
  port: 8080

spring:
  application:
    name: gateway
  # x86 device use this configuration
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
    database: ${REDIS_SESSION_DATABASE}
  # mac device with ARM chip use this configuration
  #  data:
  #    redis:
  #      host: ${REDIS_HOST}
  #      port: ${REDIS_PORT}
  #      password: ${REDIS_PASSWORD}
  #      database: ${REDIS_SESSION_DATABASE}
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600
      httpclient:
        connect-timeout: 5000
        response-timeout: 30000
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        - id: service_user
          uri: lb://user
          predicates:
            - Path=/api/user/**
        - id: product
          uri: lb://product
          predicates:
            - Path=/api/product/**

url:
  auth:
    sign-in-uri-patterns: /api/user/sign-in
    sign-up-uri-patterns: /api/user/sign-up
    sign-out-uri-patterns: /api/user/sign-out
    inner-uri-patterns: /api/**/inner/**
    trusted-uri-patterns:
      - /css/**
      - /img/**
      - /fonts/**
      - /api/product/search/**
      - /api/product/*

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9002/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

info:
  app:
    name: "gateway"
    description: "Digital Hippo gateway microservice application"
    version: "0.0.1"
