server:
  port: 8080

spring:
  # x86 device use this configuration
#  redis:
#    host: ${REDIS_HOST}
#    port: ${REDIS_PORT}
#    password: ${REDIS_PASSWORD}
#    database: ${REDIS_SESSION_DATABASE}
  # mac device with ARM chip use this configuration
    data:
      redis:
        host: ${REDIS_HOST}
        port: ${REDIS_PORT}
        password: ${REDIS_PASSWORD}
        database: ${REDIS_SESSION_DATABASE}

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9002/eureka/
