apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-dh
  namespace: digitalhippo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-dh
  template:
    metadata:
      labels:
        app: prometheus-dh
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.54.0
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
            - "--web.console.libraries=/etc/prometheus/console_libraries"
            - "--web.console.templates=/etc/prometheus/consoles"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/prometheus.yml
              subPath: prometheus.yml
      volumes:
        - name: prometheus-config-volume
          configMap:
            name: digitalhippo-general-config-map
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-dh
  namespace: digitalhippo
spec:
  type: NodePort
  selector:
    app: prometheus-dh
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30090
