apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-stripe
  namespace: digitalhippo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-stripe
  template:
    metadata:
      labels:
        app: ms-stripe
    spec:
      containers:
        - name: ms-stripe
          image: leopoldhsing2/digitalhippo.stripe:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: AWS_REGION
              value: "ca-central-1"
            - name: AWS_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: digitalhippo-aws-config-map
                  key: AWS_ENDPOINT
            - name: ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: digitalhippo-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: digitalhippo-secrets
                  key: AWS_SECRET_ACCESS_KEY
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: digitalhippo-secrets
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: digitalhippo-secrets
                  key: REDIS_PORT
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: digitalhippo-secrets
                  key: REDIS_PASSWORD
            - name: REDIS_SESSION_DATABASE
              value: "0"
            - name: POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: digitalhippo-secrets
                  key: POSTGRES_URL
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: digitalhippo-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: digitalhippo-secrets
                  key: POSTGRES_PASSWORD
            - name: ES_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: digitalhippo-secrets
                  key: ES_ENDPOINT
            - name: STRIPE_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: digitalhippo-secrets
                  key: STRIPE_WEBHOOK_SECRET
            - name: STRIPE_PUBLISHABLE_KEY
              valueFrom:
                secretKeyRef:
                  name: digitalhippo-secrets
                  key: STRIPE_PUBLISHABLE_KEY
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: digitalhippo-secrets
                  key: STRIPE_SECRET_KEY
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: ms-stripe
  namespace: digitalhippo
spec:
  selector:
    app: ms-stripe
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080