apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-email
  namespace: digitalhippo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-email
  template:
    metadata:
      labels:
        app: ms-email
    spec:
      containers:
        - name: ms-email
          image: leopoldhsing2/digitalhippo.email:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: AWS_REGION
              value: "ca-central-1"
            - name: AWS_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: digitalhippo-aws-config-map
                  key: AWS_ENDPOINT
            - name: ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: digitalhippo-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: digitalhippo-secrets
                  key: AWS_SECRET_ACCESS_KEY
            - name: FRONTEND_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: digitalhippo-general-config-map
                  key: FRONTEND_ENDPOINT
            - name: GMAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: digitalhippo-secrets
                  key: GMAIL_USERNAME
            - name: GOOGLE_APP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: digitalhippo-secrets
                  key: GOOGLE_APP_PASSWORD
            - name: RECEIPT_SQS_QUEUE_NAME
              valueFrom:
                secretKeyRef:
                  name: digitalhippo-secrets
                  key: RECEIPT_SQS_QUEUE_NAME
            - name: RECEIPT_SQS_QUEUE_URL
              valueFrom:
                secretKeyRef:
                  name: digitalhippo-secrets
                  key: RECEIPT_SQS_QUEUE_URL
            - name: VERIFICATION_SQS_QUEUE_NAME
              valueFrom:
                secretKeyRef:
                  name: digitalhippo-secrets
                  key: VERIFICATION_SQS_QUEUE_NAME
            - name: VERIFICATION_SQS_QUEUE_URL
              valueFrom:
                secretKeyRef:
                  name: digitalhippo-secrets
                  key: VERIFICATION_SQS_QUEUE_URL
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: ms-email
  namespace: digitalhippo
spec:
  selector:
    app: ms-email
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080