server:
  port: 23001
  servlet:
    context-path: /

spring:
  # x86 device use this configuration
#  redis:
#    host: localhost
#    port: 6379
#    password: 1234
#    database: 0
  # mac device with ARM chip use this configuration
  data:
    redis:
      host: localhost
      port: 6379
      password: 1234
      database: 0
  datasource:
    url: jdbc:postgresql://localhost:5432/digitalhippo
    username: postgres
    password: 1234567890
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9094


springdoc:
  api-docs:
    enabled: true
    path: /docs/v3/user/api-docs
  swagger-ui:
    path: /docs/v3/user/swagger-ui/index.html

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9000/eureka/
    enabled: true