apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  REDIS_PASSWORD: <base64-encoded-REDIS_PASSWORD>
  POSTGRES_PASSWORD: <base64-encoded-POSTGRES_PASSWORD>
  STRIPE_SECRET_KEY: <base64-encoded-STRIPE_SECRET_KEY>
  STRIPE_PUBLISHABLE_KEY: <base64-encoded-STRIPE_PUBLISHABLE_KEY>
  STRIPE_WEBHOOK_SECRET: <base64-encoded-STRIPE_WEBHOOK_SECRET>
