server:
  port: 9002

spring:
  application:
    name: eureka
  profiles:
    active: prod

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

info:
  app:
    name: "eureka"
    description: "Digital Hippo eureka server microservice application"
    version: "0.0.1"