spring:
  application:
    name: gateway
  profiles:
    active: dev
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600
      httpclient:
        connect-timeout: 5000
        response-timeout: 30000
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        - id: service_user
          uri: lb://user
          predicates:
            - Path=/api/user/**, /docs/v3/user/**
        - id: product
          uri: lb://product
          predicates:
            - Path=/api/product/**, /docs/v3/product/**
        - id: cart
          uri: lb://cart
          predicates:
            - Path=/api/cart/**, /docs/v3/cart/**
        - id: order
          uri: lb://order
          predicates:
            - Path=/api/order/**, /docs/v3/order/**

url:
  auth:
    sign-in-uri-patterns: /api/user/sign-in
    sign-up-uri-patterns: /api/user/sign-up
    sign-out-uri-patterns: /api/user/sign-out
    inner-uri-patterns: /api/**/inner/**
    public-uri-patterns:
      - /api/user/verify-email
      - /api/product/search/**
      - /api/product/*
      - /api/order/payment/confirm
      - /actuator/**
    trusted-uri-patterns:
      - /docs/v3/** # documentations

springdoc:
  api-docs:
    enabled: true
    path: /docs/v3/api-docs
  swagger-ui:
    enabled: true
    path: /docs/v3/swagger-ui/index.html
    config-url: /docs/v3/api-docs/swagger-config
    urls:
      - name: gateway
        url: /docs/v3/api-docs
      - name: user
        url: /docs/v3/user/api-docs
      - name: stripe
        url: /docs/v3/stripe/api-docs
      - name: cart
        url: /docs/v3/cart/api-docs
      - name: search
        url: /docs/v3/search/api-docs
      - name: email
        url: /docs/v3/email/api-docs
      - name: product
        url: /docs/v3/product/api-docs

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      enabled: false
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ms-gateway

endpoints:
  shutdown:
    enabled: false

info:
  app:
    name: "gateway"
    description: "Digital Hippo gateway microservice application"
    version: "0.0.1"
