server:
  port: 8080

spring:
  # mac device with ARM chip use this configuration
    data:
      redis:
        host: ${REDIS_HOST}
        port: ${REDIS_PORT}
        password: ${REDIS_PASSWORD}
        database: ${REDIS_SESSION_DATABASE}

eureka:
  instance:
    hostname: eureka
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka:8080/eureka/
