server:
  port: 8080

spring:
  # x86 device use this configuration
  redis:
    host: localhost
    port: 6379
    password: 1234
    database: 0
  # mac device with ARM chip use this configuration
#  data:
#    redis:
#      host: localhost
#      port: 6379
#      password: 1234
#      database: 0

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:23000/eureka/
