apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-cart
  namespace: digitalhippo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-cart
  template:
    metadata:
      labels:
        app: ms-cart
    spec:
      containers:
        - name: ms-cart
          image: leopoldhsing2/digitalhippo.cart:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: digitalhippo-secrets
                  key: POSTGRES_URL
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: digitalhippo-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: digitalhippo-secrets
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: ms-cart
  namespace: digitalhippo
spec:
  selector:
    app: ms-cart
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080