apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-user
  namespace: digitalhippo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-user
  template:
    metadata:
      labels:
        app: ms-user
    spec:
      containers:
        - name: ms-user
          image: leopoldhsing2/digitalhippo.user:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: AWS_REGION
              value: "ca-central-1"
            - name: AWS_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: digitalhippo-aws-config-map
                  key: AWS_ENDPOINT
            - name: ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: digitalhippo-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: digitalhippo-secrets
                  key: AWS_SECRET_ACCESS_KEY
            - name: SNS_TOPIC_ARN
              valueFrom:
                secretKeyRef:
                  name: digitalhippo-secrets
                  key: SNS_TOPIC_ARN
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: digitalhippo-secrets
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: digitalhippo-secrets
                  key: REDIS_PORT
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: digitalhippo-secrets
                  key: REDIS_PASSWORD
            - name: REDIS_SESSION_DATABASE
              value: "0"
            - name: POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: digitalhippo-secrets
                  key: POSTGRES_URL
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: digitalhippo-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: digitalhippo-secrets
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: ms-user
  namespace: digitalhippo
spec:
  selector:
    app: ms-user
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080