apiVersion: v1
kind: ConfigMap
metadata:
  name: digitalhippo-aws-config-map
  namespace: digitalhippo
data:
  AWS_REGION: "ca-central-1"
  public-read-policy.json: |
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Effect": "Allow",
          "Principal": "*",
          "Action": "s3:GetObject",
          "Resource": "arn:aws:s3:::digitalhippo-leopoldxing/*"
        }
      ]
    }
