apiVersion: v1
kind: ConfigMap
metadata:
  name: digitalhippo-elk-config-map
  namespace: digitalhippo
data:
  kibana.yml: |
    server.port: 5601
    server.host: "0.0.0.0"
    elasticsearch.hosts: [ "*******" ]
    monitoring.ui.container.elasticsearch.enabled: true
  logstash.yml: |
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
    xpack.monitoring.enabled: true
    xpack.monitoring.elasticsearch.hosts: [ "********" ]
  logstash.conf: |
    input {
        tcp{
            port => 5000
            codec => json
        }
    }
      output{
      elasticsearch{
      hosts => ["********"]
      index => "digitalhippo-logs-%{microservice}"
      }
    }
