apiVersion: v1
kind: ConfigMap
metadata:
  name: digitalhippo-elk-config-map
  namespace: digitalhippo
data:
  ES_ENDPOINT: "http://elasticsearch-external:9200"
  logstash.yml: |
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
    xpack.monitoring.enabled: true
    xpack.monitoring.elasticsearch.hosts: [ "elasticsearch-external:9200" ]
  logstash.conf: |
    input {
        tcp{
            port => 5000
            codec => json
        }
    }
      output{
      elasticsearch{
      hosts => ["elasticsearch-external:9200"]
      index => "digitalhippo-logs-%{microservice}"
      }
    }
