apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-product
  namespace: digitalhippo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-product
  template:
    metadata:
      labels:
        app: ms-product
    spec:
      containers:
        - name: ms-product
          image: leopoldhsing2/digitalhippo.product:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: digitalhippo-db-config-map
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: digitalhippo-db-config-map
                  key: REDIS_PORT
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: digitalhippo-secrets
                  key: REDIS_PASSWORD
            - name: REDIS_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: digitalhippo-db-config-map
                  key: REDIS_CACHING_DATABASE
            - name: POSTGRES_URL
              valueFrom:
                configMapKeyRef:
                  name: digitalhippo-db-config-map
                  key: POSTGRES_URL
            - name: POSTGRES_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: digitalhippo-db-config-map
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: digitalhippo-secrets
                  key: POSTGRES_PASSWORD
            - name: ES_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: digitalhippo-elk-config-map
                  key: ES_ENDPOINT
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: ms-product
  namespace: digitalhippo
spec:
  selector:
    app: ms-product
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080