services:
  redis:
    image: redis:7.0.14
    container_name: redis-digitalhippo-dev
    environment:
      - REDIS_PASSWORD=1234
    command: [ "redis-server", "--requirepass", "1234" ]
    ports:
      - "6379:6379"
    networks:
      - digitalhippo-dev-network
  postgres:
    image: postgres:16.4-alpine
    container_name: postgres-digitalhippo-dev
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 1234567890
    networks:
      - digitalhippo-dev-network
  mongodb:
    image: mongodb/mongodb-community-server:7.0.5-ubi8
    container_name: digitalhippo-mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=lupin
      - MONGO_INITDB_ROOT_PASSWORD=1234
    ports:
      - "27017:27017"
    networks:
      - digitalhippo-dev-network

networks:
  digitalhippo-dev-network:
    name: digitalhippo-dev-network
    driver: bridge