server:
  port: 9006

spring:
  application:
    name: product
  datasource:
    url: jdbc:postgresql://localhost:5432/digitalhippo
    username: postgres
    password: 1234567890
  jpa:
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
      password: 1234
      database: 2
  elasticsearch:
    uris:
      - http://localhost:9200
    username: elastic
    password:

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9002/eureka/